### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hmajoros** [hmajoros/web#4]
### Urgent Todo's
- [x] create jinja partials for all reused code (projects / work pages). Create objects in python
- [x] contact page with [sendgrid](https://github.com/sendgrid/sendgrid-python#example) for emails to my inbox
- [ ] mobile navigation (FIX BUG ON iPHONE)
- [x] update resume
- [ ] finalize all site colors
- [x] base layout for section pages
- [x] component for work experience (md-card)
- [x] component for skills
- [ ] component for photos page (use [this - layout](http://www.bootply.com/1Tq35rlkbx), and [this - backend](http://stackoverflow.com/questions/3964681/find-all-files-in-directory-with-extension-txt-with-python))
- [x] component projects (cards again?)
- [x] fix weird header hover bug
- [x] favicon
### fun extras
- [ ] instagram api for recent photos (link [here](https://github.com/Instagram/python-instagram))
- [ ] lots of animations
### Final checks
- [ ] clean up all unneeded sass
- [ ] clean up javascript files
- [ ] clean up html templates
